Update CI

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -2,40 +2,40 @@ name: ci
 on:
   push:
     branches:
-      - develop
+      - main
   pull_request:
     branches:
-      - develop
+      - main
 
 jobs:
 
   test_node:
-    runs-on: ubuntu-latest
-    if: ${{ !github.event.created }}
+    runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        node: [ '14', '13', '12', '11', '10', '8' ]
-    name: Test with Node v${{ matrix.node }}
+        node: [ '14', '15' ,'16', '17' ]
+        os: [ windows-latest, ubuntu-latest ]
+    name: Test with Node v${{ matrix.node }} on ${{ matrix.os }}
     steps:
-
-    - uses: actions/checkout@v2
-    - uses: actions/setup-node@v1
+    - uses: actions/checkout@v3
+    - uses: actions/setup-node@v3
       with:
         node-version: ${{ matrix.node }}
-    - run: npm ci
-    - run: npx tsc
-    - run: npm run test:node
-
+    - uses: bahmutov/npm-install@v1
+    - run: yarn build
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
+    - run: yarn test:node
   test_deno:
     runs-on: ubuntu-latest
-    if: ${{ !github.event.created }}
     name: test with Deno
     steps: 
-
-    - uses: actions/checkout@v2
-    - uses: actions/setup-node@v1
+    - uses: actions/checkout@v3
+    - uses: actions/setup-node@v3
+      with:
+        node-version: '15'
     - name: Cache
-      uses: actions/cache@v1
+      uses: actions/cache@v3
       with:
         path: ~/.cache/deno
         key: deno-${{ runner.os }}-${{ hashFiles('deno-lock.json') }}
@@ -43,61 +43,105 @@ jobs:
            deno-${{ runner.os }}-${{ hashFiles('deno-lock.json') }}
            deno-${{ runner.os }}-
            deno-
-    - uses: denolib/setup-deno@master
+    - uses: denoland/setup-deno@v1
       with:
         deno-version: v1.x
     - run: deno --version
-    - run: npm ci
-    - run: npm run build
-    - run: npm run test:deno
-
-  trigger_publish:
-    name: Trigger publish.yaml workflow if package.json version updated ( and secrets.PAT is set ).
+    - uses: bahmutov/npm-install@v1
+    - run: yarn build
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
+    - run: yarn test:deno
+  check_if_version_upgraded:
+    name: Check if version upgrade
+    # We run this only if it's a push on the default branch or if it's a PR from a 
+    # branch (meaning not a PR from a fork). It would be more straightforward to test if secrets.NPM_TOKEN is 
+    # defined but GitHub Action don't allow it yet.
+    if: |
+      github.event_name == 'push' || 
+      github.event.pull_request.head.repo.owner.login == github.event.pull_request.base.repo.owner.login 
     runs-on: ubuntu-latest
-    env:
-      PAT: ${{secrets.PAT}}
-    if: github.event_name == 'push' && github.event.head_commit.author.name != 'denoify_ci'
-    needs:
+    needs: 
       - test_node
       - test_deno
+    outputs:
+      from_version: ${{ steps.step1.outputs.from_version }}
+      to_version: ${{ steps.step1.outputs.to_version }}
+      is_upgraded_version: ${{ steps.step1.outputs.is_upgraded_version }}
+      is_pre_release: ${{steps.step1.outputs.is_pre_release }}
     steps:
-
-    - name: Get version on latest
-      id: v_latest
-      uses: garronej/github_actions_toolkit@v1.4
+    - uses: garronej/ts-ci@v2.1.0
+      id: step1
       with: 
-        action_name: get_package_json_version
-        owner: ${{github.repository_owner}}
-        repo: ${{github.event.repository.name}}
-        branch: latest
-        compare_to_version: '0.0.0'
+        action_name: is_package_json_version_upgraded
+        branch: ${{ github.head_ref || github.ref }}
 
-    - name: Get version on develop
-      id: v_develop
-      uses: garronej/github_actions_toolkit@v1.4
-      with: 
-        action_name: get_package_json_version
-        owner: ${{github.repository_owner}}
-        repo: ${{github.event.repository.name}}
-        branch: ${{ github.sha }}
-        compare_to_version: ${{steps.v_latest.outputs.version || '0.0.0'}}
-
-    - name: 'Trigger the ''publish'' workflow' 
-      if: ${{ !!env.PAT && steps.v_develop.outputs.compare_result == '1' }}
-      uses: garronej/github_actions_toolkit@v1.4
-      env:
-        GITHUB_TOKEN: ${{ secrets.PAT }} 
+  publish:
+    runs-on: ubuntu-latest
+    needs: 
+      - check_if_version_upgraded
+    # We create a release only if the version have been upgraded and we are on the main branch
+    # or if we are on a branch of the repo that has an PR open on main.
+    if: |
+      needs.check_if_version_upgraded.outputs.is_upgraded_version == 'true' &&
+      (
+        github.event_name == 'push' ||
+        needs.check_if_version_upgraded.outputs.is_pre_release == 'true'
+      )
+    steps:
+    - uses: actions/checkout@v3
       with:
-        action_name: dispatch_event
-        owner: ${{github.repository_owner}}
-        repo: ${{github.event.repository.name}}
-        event_type: publish
-        client_payload_json: |
-          ${{
-            format(
-              '{{"from_version":"{0}","to_version":"{1}","repo":"{2}"}}',
-              steps.v_latest.outputs.version,
-              steps.v_develop.outputs.version,
-              github.event.repository.name
-            )
-          }}
+        fetch-depth: 0
+        ref: ${{ github.ref }}
+    - run: rm -r .github
+    - name: Remove tmp_branch if it exists
+      run: git push origin :tmp_branch || true
+    - run: git checkout -b tmp_branch
+    - uses: actions/setup-node@v3
+      with:
+        registry-url: https://registry.npmjs.org/
+    - uses: bahmutov/npm-install@v1
+    - run: yarn build
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
+    - run: |
+        npx -y -p denoify@1.4.8 enable_short_npm_import_path
+        npx -y -p denoify@1.4.8 remove_deno_dist_from_gitignore
+      env:
+        DRY_RUN: "0"
+    - run: |
+        if [ "$(npm show . version)" = "$VERSION" ]; then
+          echo "This version is already published"
+          exit 0
+        fi
+        if [ "$NODE_AUTH_TOKEN" = "" ]; then
+          echo "Can't publish on NPM, You must first create a secret called NPM_TOKEN that contains your NPM auth token. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets"
+          false
+        fi
+        EXTRA_ARGS=""
+        if [ "$IS_PRE_RELEASE" = "true" ]; then
+            EXTRA_ARGS="--tag next"
+        fi
+        npm publish $EXTRA_ARGS
+      env:
+        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
+        VERSION: ${{ needs.check_if_version_upgraded.outputs.to_version }}
+        IS_PRE_RELEASE: ${{ needs.check_if_version_upgraded.outputs.is_pre_release }}
+    - run: |
+        git config --global user.name "actions"
+        git config --global user.email actions@github.com
+        git add -A
+        git commit -am "Adding deno distribution files and moving files from /dist to /"
+        git push origin tmp_branch
+    - uses: softprops/action-gh-release@v1
+      with:
+        name: Release v${{ needs.check_if_version_upgraded.outputs.to_version }}
+        tag_name: v${{ needs.check_if_version_upgraded.outputs.to_version }}
+        target_commitish: tmp_branch
+        generate_release_notes: false
+        draft: false
+        prerelease: ${{ needs.check_if_version_upgraded.outputs.is_pre_release == 'true' }}
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
+    - name: Remove tmp_branch
+      run: git push origin :tmp_branch
