Update denoify

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -38,7 +38,7 @@ jobs:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v1
     - run: npm ci
-    - run: npm run enable_short_import_path:npm
+    - run: npm run enable_short_import_path
       env:
         DRY_RUN: "0"
     - name: (DEBUG) Show how the files have been moved to enable short import
@@ -60,6 +60,8 @@ jobs:
         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
         MODULE_NAME: ${{ github.event.client_payload.repo }}
         VERSION: ${{ github.event.client_payload.to_version }}
+
+
   publish_deno:
     runs-on: ubuntu-latest
     needs: update_changelog_and_sync_package_lock_version
@@ -68,22 +70,41 @@ jobs:
       with:
         fetch-depth: 0
         ref: develop
-    - name: Remove .github directory, useless on 'master' branch
+    - name: Remove .github directory, useless on 'latest' branch
       run: rm -r .github
-    - name: Remove branch 'master' 
+    - name: Remove branch 'latest' 
       continue-on-error: true
       run: |
-        git branch -d master || true
-        git push origin :master
-    - name: Create the new 'master' branch
+        git branch -d latest || true
+        git push origin :latest
+    - name: Create the new 'latest' branch
       run: |
-        git branch master
-        git checkout master
+        git branch latest
+        git checkout latest
     - uses: actions/setup-node@v1
     - run: npm ci
-    - run: npm run enable_short_import_path:deno
+    - run: npm run enable_short_import_path
       env:
         DRY_RUN: "0"
+    - name: (DEBUG) Show how the files have been moved to enable short import
+      run: ls -lR
+    - name: Publishing on NPM
+      run: |
+        if [ "$(npm show $MODULE_NAME version)" = "$VERSION" ]; then
+          echo "This version is already published"
+          exit 0
+        fi
+        if [ "$NPM_TOKEN" = "" ]; then
+          echo "Can't publish on NPM, You must first create a secret called NPM_TOKEN that contains your NPM auth token. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets"
+          false
+        fi
+        echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
+        npm publish
+        rm .npmrc
+      env:
+        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+        MODULE_NAME: ${{ github.event.client_payload.repo }}
+        VERSION: ${{ github.event.client_payload.to_version }}
     - name: Commit changes
       run: |
         git config --local user.email "denoify_ci@github.com"
@@ -103,14 +124,14 @@ jobs:
         FROM_VERSION: ${{ github.event.client_payload.from_version }}
         OWNER: ${{github.repository_owner}}
         REPO: ${{github.event.client_payload.repo}}
-        REF: ${{github.event.client_payload.to_version}}
+        REF: v${{github.event.client_payload.to_version}}
     - name: Create Release
       uses: garronej/create-release@master
       env:
         GITHUB_TOKEN: ${{ secrets.PAT }} 
       with:
-        tag_name: ${{ github.event.client_payload.to_version }}
-        release_name: Release ${{ github.event.client_payload.to_version }}
+        tag_name: v${{ github.event.client_payload.to_version }}
+        release_name: Release v${{ github.event.client_payload.to_version }}
         branch: master
         draft: false
         prerelease: false
